apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::730022907366:role/eksctl-fiap-cluster-ServiceRole-11HHS0AZ0BFMR
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
